version: "3.5"
services:
  
  php:
    build:
      context: php
    ports:
    - 80:80
    volumes:
      - ./app:/var/www/html
    links:
      - mariadb
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4
    command: --init-file /data/application/init.sql
    ports:
    - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root!
      MYSQL_DATABASE: mariadb
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_user!
    volumes:
      - ./databases/mariadb:/var/lib/mysql
      - ./init.sql:/data/application/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    ports:
    - 127.0.0.1:8080:8080
    environment:
      PMA_HOST: mariadb
      PMA_USER: test_user
      PMA_PASSWORD: test_user!
